import type {Metadata} from 'next'
import {Golos_Text} from 'next/font/google'
import Script from 'next/script'
import './globals.css'

const golosText = Golos_Text({
  variable: '--font-golos-text',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={golosText.variable}>
        {children}
        <Script
          src="https://timeweb.cloud/api/v1/cloud-ai/agents/627a97d4-e893-4f60-92eb-f5462dd08092/embed.js?collapsed=true"
          strategy="afterInteractive"
        />
      </body>
    </html>
  )
}
