import type {Metadata} from 'next'
import { unstable_cache } from 'next/cache'
import {Golos_Text} from 'next/font/google'
import Script from 'next/script'
import { AppShell } from '@/components/app-shell'
import { sidebarCaseItemsQuery } from '@/lib/sanity/queries'
import { sanityClient } from '@/lib/sanity/client'
import type { SidebarCaseItem } from '@/lib/sanity/types'
import { TooltipProvider } from '@/ui-kit'
import './globals.css'

const golosText = Golos_Text({
  variable: '--font-golos-text',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const getSidebarCaseItems = unstable_cache(
  async () => sanityClient.fetch<SidebarCaseItem[]>(sidebarCaseItemsQuery),
  ['sidebar-case-items'],
  { revalidate: 300 }
)

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const sidebarCaseItems = await getSidebarCaseItems()

  return (
    <html lang="en">
      <body className={golosText.variable}>
        <TooltipProvider>
          <AppShell sidebarCaseItems={sidebarCaseItems}>{children}</AppShell>
        </TooltipProvider>
        <Script
          src="https://timeweb.cloud/api/v1/cloud-ai/agents/627a97d4-e893-4f60-92eb-f5462dd08092/embed.js?collapsed=true"
          strategy="afterInteractive"
        />
      </body>
    </html>
  )
}
